key = "" #输入你的APIKEY
port = "" #指定端口 (默认全部, 可用英文逗号分隔)
asn = "" #指定ASN (默认全部, 可用英文逗号分隔)
region = "" #指定地区ISO3166二字码 (默认全部, 可用英文逗号分隔)
output = "" #指定输出文件 (默认ip.txt)

# 以下选项为开关项，true为开启，false为关闭，不要加双引号
norepeat = false # 自动去除重复IP (默认不去除)
auto = false # 自动获取下一页内容 (默认需要确认)